project:
  name: customer-churn
  version: 1.0.0

files:
  raw_file: customer_churn.csv
  interim_file: customer_churn_cleaned.csv
  processed_file: customer_churn_features.csv

data:
  target: Churn Value
  test_size: 0.2
  validation_size: 0.1
  random_state: 42

feature_engineering:
  required_columns:
  - Tenure Months
  - Total Charges
  - CLTV
  
  drop_columns:
  - CustomerID
  - Count
  - Churn Label
  - Churn Score
  - Churn Reason

  drop_location_columns:
  - Zip Code
  - Lat Long
  - Latitude
  - Longitude
  - Country
  - State

  tenure_bins:
  - 0
  - 12
  - 36
  - 72

  tenure_labels:
  - New
  - Medium
  - Loyal

  high_value_strategy: Median

training:
  model: xgboost

logging:
  level: INFO


#   raw_path: data/raw/customer_churn.csv
#   interim_file: data/interim/customer_churn_cleaned.csv
#   processed_path: data/processed/
#   processed_file: data/processed/customer_churn_features.csv
#   train_path: data/processed/train.csv
#   test_path: data/processed/test.csv

# model:
#   target: Churn Value
#   test_size: 0.2
#   random_state: 42

# artifacts:
#   model_path: artifacts/model.pkl